#!/bin/sh

client="mvn exec:java -Dexec.mainClass="sd.client.Main""
server="mvn exec:java -Dexec.mainClass="sd.server.Main""

tmux new-session "$server; read" \; split-window -h "sleep 2s; $client" \;
